# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - master
name: "DropWordStaging"
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Staging'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: 'test.zip'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$test.zip'
    replaceExistingArchive: true
    
# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'DropWordPipline'
#     appType: 'webAppLinux'
#     WebAppName: 'web-drop-word-test'
#     packageForLinux: '$(Build.ArtifactStagingDirectory)/$test.zip'
#     RuntimeStack: 'DOTNETCORE|7.0'

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'DropWordPipline'
#     appType: 'webAppLinux'
#     WebAppName: 'web-drop-word-test'
#     packageForLinux: '$(Build.ArtifactStagingDirectory)/$test.zip'
#     RuntimeStack: 'DOTNETCORE|7.0'
#     StartupCommand: 'dotnet /src/TgBot/bin/Debug/net8.0/DropWord.TgBot.dll'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'DropWordPipline'
    appType: 'webApp'
    WebAppName: 'web-drop-word-test-win'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$test.zip'
    StartupCommand: 'dotnet /src/TgBot/bin/Debug/net8.0/DropWord.TgBot.dll'
